trigger:
- master

stages:
 - stage: Build
   jobs:
   - job: Build   
     pool:
       vmImage: 'ubuntu-latest'
     variables:
       buildConfiguration: 'Release'
       rid: 'linux-x64'
     steps:
      - task: UseDotNet@2
        inputs:
          version: '3.1.x'
          packageType: sdk
      
      - task: DotNetCoreCLI@2
        displayName: 'dotnet build $(buildConfiguration)'
        inputs:
          command: 'build'
          arguments: '-r $(rid) --configuration $(buildConfiguration) /p:SourceRevisionId=$(Build.SourceVersion)'

      - task: DotNetCoreCLI@2
        inputs:
          command: 'publish'
          publishWebProjects: true
          arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'cicd-sample'
          publishLocation: 'Container'
  
 - stage: Deploy
   jobs:
   - job: Deploy
     pool:
       vmImage: 'ubuntu-latest'
     steps:
      - task: DownloadBuildArtifacts@0
        inputs:
          buildType: 'current'
          downloadType: 'specific'
          downloadPath: '$(System.ArtifactsDirectory)'
          artifactName: 'cicd-sample'
      
      - task: AzureWebApp@1
        inputs:
          azureSubscription: $azureserviceconnection
          appType: 'webAppLinux'
          appName: $webappname
          package: '$(System.ArtifactsDirectory)/**/*.zip'